spring.application.name=tpejemplo

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:tpdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=localhost
spring.datasource.password=password123

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Inicializacion de datos
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:import.sql

# Consola H2 (solo desarrollo)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Puerto
server.port=8080

# JWT
jwt.secret=Kq9X3n#5Vt7!rP2$zH8@uL4%wC6^mY1&bN0*QfD3gS5hJ7kL9pZ2xR4
jwt.expiration-ms=86400000
